import Layaut from "../components/Template/Layaut";
import Head from "next/head";
export default function Home() {
  return (
    <Layaut>
      <Head>
        <title>Milton Developer</title>
      </Head>
      <div className="Home">
        Milton Estrada
      </div>
      <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorum, sint quibusdam, suscipit quos nemo voluptatum repellat praesentium sed vitae amet dolorem eos fugit. Assumenda distinctio id quo tempora error reprehenderit labore adipisci voluptatem exercitationem est, nulla ullam magnam ipsum. Accusantium expedita fugiat quam ex at aut optio qui, rerum quaerat harum autem eveniet id? Accusantium aperiam quis maxime ex quisquam ipsum eligendi quam repellendus cumque. Explicabo voluptatem, autem possimus laborum veniam veritatis incidunt reprehenderit voluptatum? Repellendus velit commodi consequatur facere minima assumenda accusantium iure libero at consequuntur eum consectetur autem deleniti dolor minus voluptatibus animi, totam cum eos impedit ut itaque rem tenetur? Nesciunt consequatur quibusdam officia, rerum voluptatibus, veritatis rem tempora quaerat quasi error explicabo delectus ipsa. Earum, mollitia vero dolore, at aliquam voluptatibus, eos ullam itaque saepe tempore autem quod corrupti alias vitae fugit? Nemo magnam ut id natus asperiores, tenetur minima ratione perferendis. Doloremque dolorum natus officiis id enim, ratione nostrum, unde eos velit dolor error quibusdam reiciendis cumque similique eaque quam aspernatur fugiat. A quam repellendus quia rerum est iure voluptatibus, tenetur laboriosam nemo aspernatur? Minima consequatur at error, eum officia ipsam quibusdam, corporis sit, fuga nulla perferendis optio quasi reprehenderit cupiditate est neque accusamus. Deserunt.
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorum, sint quibusdam, suscipit quos nemo voluptatum repellat praesentium sed vitae amet dolorem eos fugit. Assumenda distinctio id quo tempora error reprehenderit labore adipisci voluptatem exercitationem est, nulla ullam magnam ipsum. Accusantium expedita fugiat quam ex at aut optio qui, rerum quaerat harum autem eveniet id? Accusantium aperiam quis maxime ex quisquam ipsum eligendi quam repellendus cumque. Explicabo voluptatem, autem possimus laborum veniam veritatis incidunt reprehenderit voluptatum? Repellendus velit commodi consequatur facere minima assumenda accusantium iure libero at consequuntur eum consectetur autem deleniti dolor minus voluptatibus animi, totam cum eos impedit ut itaque rem tenetur? Nesciunt consequatur quibusdam officia, rerum voluptatibus, veritatis rem tempora quaerat quasi error explicabo delectus ipsa. Earum, mollitia vero dolore, at aliquam voluptatibus, eos ullam itaque saepe tempore autem quod corrupti alias vitae fugit? Nemo magnam ut id natus asperiores, tenetur minima ratione perferendis. Doloremque dolorum natus officiis id enim, ratione nostrum, unde eos velit dolor error quibusdam reiciendis cumque similique eaque quam aspernatur fugiat. A quam repellendus quia rerum est iure voluptatibus, tenetur laboriosam nemo aspernatur? Minima consequatur at error, eum officia ipsam quibusdam, corporis sit, fuga nulla perferendis optio quasi reprehenderit cupiditate est neque accusamus. Deserunt.
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorum, sint quibusdam, suscipit quos nemo voluptatum repellat praesentium sed vitae amet dolorem eos fugit. Assumenda distinctio id quo tempora error reprehenderit labore adipisci voluptatem exercitationem est, nulla ullam magnam ipsum. Accusantium expedita fugiat quam ex at aut optio qui, rerum quaerat harum autem eveniet id? Accusantium aperiam quis maxime ex quisquam ipsum eligendi quam repellendus cumque. Explicabo voluptatem, autem possimus laborum veniam veritatis incidunt reprehenderit voluptatum? Repellendus velit commodi consequatur facere minima assumenda accusantium iure libero at consequuntur eum consectetur autem deleniti dolor minus voluptatibus animi, totam cum eos impedit ut itaque rem tenetur? Nesciunt consequatur quibusdam officia, rerum voluptatibus, veritatis rem tempora quaerat quasi error explicabo delectus ipsa. Earum, mollitia vero dolore, at aliquam voluptatibus, eos ullam itaque saepe tempore autem quod corrupti alias vitae fugit? Nemo magnam ut id natus asperiores, tenetur minima ratione perferendis. Doloremque dolorum natus officiis id enim, ratione nostrum, unde eos velit dolor error quibusdam reiciendis cumque similique eaque quam aspernatur fugiat. A quam repellendus quia rerum est iure voluptatibus, tenetur laboriosam nemo aspernatur? Minima consequatur at error, eum officia ipsam quibusdam, corporis sit, fuga nulla perferendis optio quasi reprehenderit cupiditate est neque accusamus. Deserunt.
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorum, sint quibusdam, suscipit quos nemo voluptatum repellat praesentium sed vitae amet dolorem eos fugit. Assumenda distinctio id quo tempora error reprehenderit labore adipisci voluptatem exercitationem est, nulla ullam magnam ipsum. Accusantium expedita fugiat quam ex at aut optio qui, rerum quaerat harum autem eveniet id? Accusantium aperiam quis maxime ex quisquam ipsum eligendi quam repellendus cumque. Explicabo voluptatem, autem possimus laborum veniam veritatis incidunt reprehenderit voluptatum? Repellendus velit commodi consequatur facere minima assumenda accusantium iure libero at consequuntur eum consectetur autem deleniti dolor minus voluptatibus animi, totam cum eos impedit ut itaque rem tenetur? Nesciunt consequatur quibusdam officia, rerum voluptatibus, veritatis rem tempora quaerat quasi error explicabo delectus ipsa. Earum, mollitia vero dolore, at aliquam voluptatibus, eos ullam itaque saepe tempore autem quod corrupti alias vitae fugit? Nemo magnam ut id natus asperiores, tenetur minima ratione perferendis. Doloremque dolorum natus officiis id enim, ratione nostrum, unde eos velit dolor error quibusdam reiciendis cumque similique eaque quam aspernatur fugiat. A quam repellendus quia rerum est iure voluptatibus, tenetur laboriosam nemo aspernatur? Minima consequatur at error, eum officia ipsam quibusdam, corporis sit, fuga nulla perferendis optio quasi reprehenderit cupiditate est neque accusamus. Deserunt.
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorum, sint quibusdam, suscipit quos nemo voluptatum repellat praesentium sed vitae amet dolorem eos fugit. Assumenda distinctio id quo tempora error reprehenderit labore adipisci voluptatem exercitationem est, nulla ullam magnam ipsum. Accusantium expedita fugiat quam ex at aut optio qui, rerum quaerat harum autem eveniet id? Accusantium aperiam quis maxime ex quisquam ipsum eligendi quam repellendus cumque. Explicabo voluptatem, autem possimus laborum veniam veritatis incidunt reprehenderit voluptatum? Repellendus velit commodi consequatur facere minima assumenda accusantium iure libero at consequuntur eum consectetur autem deleniti dolor minus voluptatibus animi, totam cum eos impedit ut itaque rem tenetur? Nesciunt consequatur quibusdam officia, rerum voluptatibus, veritatis rem tempora quaerat quasi error explicabo delectus ipsa. Earum, mollitia vero dolore, at aliquam voluptatibus, eos ullam itaque saepe tempore autem quod corrupti alias vitae fugit? Nemo magnam ut id natus asperiores, tenetur minima ratione perferendis. Doloremque dolorum natus officiis id enim, ratione nostrum, unde eos velit dolor error quibusdam reiciendis cumque similique eaque quam aspernatur fugiat. A quam repellendus quia rerum est iure voluptatibus, tenetur laboriosam nemo aspernatur? Minima consequatur at error, eum officia ipsam quibusdam, corporis sit, fuga nulla perferendis optio quasi reprehenderit cupiditate est neque accusamus. Deserunt.
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorum, sint quibusdam, suscipit quos nemo voluptatum repellat praesentium sed vitae amet dolorem eos fugit. Assumenda distinctio id quo tempora error reprehenderit labore adipisci voluptatem exercitationem est, nulla ullam magnam ipsum. Accusantium expedita fugiat quam ex at aut optio qui, rerum quaerat harum autem eveniet id? Accusantium aperiam quis maxime ex quisquam ipsum eligendi quam repellendus cumque. Explicabo voluptatem, autem possimus laborum veniam veritatis incidunt reprehenderit voluptatum? Repellendus velit commodi consequatur facere minima assumenda accusantium iure libero at consequuntur eum consectetur autem deleniti dolor minus voluptatibus animi, totam cum eos impedit ut itaque rem tenetur? Nesciunt consequatur quibusdam officia, rerum voluptatibus, veritatis rem tempora quaerat quasi error explicabo delectus ipsa. Earum, mollitia vero dolore, at aliquam voluptatibus, eos ullam itaque saepe tempore autem quod corrupti alias vitae fugit? Nemo magnam ut id natus asperiores, tenetur minima ratione perferendis. Doloremque dolorum natus officiis id enim, ratione nostrum, unde eos velit dolor error quibusdam reiciendis cumque similique eaque quam aspernatur fugiat. A quam repellendus quia rerum est iure voluptatibus, tenetur laboriosam nemo aspernatur? Minima consequatur at error, eum officia ipsam quibusdam, corporis sit, fuga nulla perferendis optio quasi reprehenderit cupiditate est neque accusamus. Deserunt.
      </p>
      <p>
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolorum, sint quibusdam, suscipit quos nemo voluptatum repellat praesentium sed vitae amet dolorem eos fugit. Assumenda distinctio id quo tempora error reprehenderit labore adipisci voluptatem exercitationem est, nulla ullam magnam ipsum. Accusantium expedita fugiat quam ex at aut optio qui, rerum quaerat harum autem eveniet id? Accusantium aperiam quis maxime ex quisquam ipsum eligendi quam repellendus cumque. Explicabo voluptatem, autem possimus laborum veniam veritatis incidunt reprehenderit voluptatum? Repellendus velit commodi consequatur facere minima assumenda accusantium iure libero at consequuntur eum consectetur autem deleniti dolor minus voluptatibus animi, totam cum eos impedit ut itaque rem tenetur? Nesciunt consequatur quibusdam officia, rerum voluptatibus, veritatis rem tempora quaerat quasi error explicabo delectus ipsa. Earum, mollitia vero dolore, at aliquam voluptatibus, eos ullam itaque saepe tempore autem quod corrupti alias vitae fugit? Nemo magnam ut id natus asperiores, tenetur minima ratione perferendis. Doloremque dolorum natus officiis id enim, ratione nostrum, unde eos velit dolor error quibusdam reiciendis cumque similique eaque quam aspernatur fugiat. A quam repellendus quia rerum est iure voluptatibus, tenetur laboriosam nemo aspernatur? Minima consequatur at error, eum officia ipsam quibusdam, corporis sit, fuga nulla perferendis optio quasi reprehenderit cupiditate est neque accusamus. Deserunt.
      </p>
    </Layaut>
  );
}
